"""d2_documents

Revision ID: 9131c1974bd1
Revises: 3271d4bba485
Create Date: 2025-12-29 02:45:13.041960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9131c1974bd1'
down_revision: Union[str, None] = '3271d4bba485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploader_user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('minio_key_original', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_org_case_created', 'documents', ['org_id', 'case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('minio_key_page_pdf', sa.String(), nullable=False),
    sa.Column('minio_key_thumbnail', sa.String(), nullable=True),
    sa.Column('ocr_status', sa.String(), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_pages_org_doc_page', 'document_pages', ['org_id', 'document_id', 'page_number'], unique=False)
    op.create_index(op.f('ix_document_pages_org_id'), 'document_pages', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_pages_org_id'), table_name='document_pages')
    op.drop_index('idx_document_pages_org_doc_page', table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index('idx_documents_org_case_created', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###

